# For more info on HTTP files go to https://aka.ms/vs/httpfile
# An http-client.env.json should be created in the root directory of the project. 
# Select the environment in the upper right corner of this file.

# File level variables
@ApiVersion = v1
@RequestedBy = Fleet.Api.Tests
@id = ff3875f1-ac9b-4549-a9e8-c8d2aac1e81d
@stationId = "55bc2233-8663-45cc-ae71-0eb38c95a7eb"
@measurementUnitCode = "mph"
@deviceIdentifier = "DEV-RPI-0001"

### Get All Sensors
GET {{HostAddress}}/api/{{ApiVersion}}/sensors

###

### Get Sensor by ID
GET {{HostAddress}}/api/{{ApiVersion}}/sensors/{{id}}

###

### Create Sensor
POST {{HostAddress}}/api/{{ApiVersion}}/sensors
Content-Type: application/json

{
  "sensorTypeName": "LTWind",
  "stationId": {{stationId}},
  "deviceIdentifier": {{deviceIdentifier}},
  "sensorStatusCode": "ACTIVE",
  "measurementUnitCode": {{measurementUnitCode}},
  "sensorIdentifier": "SNS-LTW-0001"
}

###

### Update Sensor
PUT {{HostAddress}}/api/{{ApiVersion}}/sensors/{{id}}
Content-Type: application/json

{
  "id": "{{id}}",
  "sensorTypeName": "AethLabs",
  "stationId": {{stationId}},
  "deviceIdentifier": {{deviceIdentifier}},
  "sensorStatusCode": "ACTIVE",
  "measurementUnitCode": {{measurementUnitCode}},
  "sensorIdentifier": "SNS-AL80-0031"
}

###
