# For more info on HTTP files go to https://aka.ms/vs/httpfile
# An http-client.env.json should be created in the root directory of the project. 
# Select the environment in the upper right corner of this file.

# File level variables
@ApiVersion = v1
@RequestedBy = Fleet.Api.Tests
@id = 4a9d9369-ea6b-402d-8673-5f77fcda8681

### Get All Sites
GET {{HostAddress}}/api/{{ApiVersion}}/sites

###

### Get Site by ID
GET {{HostAddress}}/api/{{ApiVersion}}/sites/{{id}}

###

### Get All Stations for a Site
GET {{HostAddress}}/api/{{ApiVersion}}/sites/{{id}}/stations

###

### Create a new Site
POST {{HostAddress}}/api/{{ApiVersion}}/sites
Content-Type: application/json

{
  "siteStatusCode": "ACTIVE",
  "siteName": "1560 Drew Ave, Davis",
  "siteCode": "SITE-DAVIS-DREW-AVE",
  "addressLine1": "1560 Drew Avenue",
  "addressLine2": null,
  "city": "Davis",
  "state": "CA",
  "postalCode": "95616",
  "country": "USA",
  "latitude": 38.5449,
  "longitude": -121.7405,
  "installedAtUtc": "2025-12-15T14:30:00Z",
  "lastMaintenanceAtUtc": "2026-06-22T09:45:00Z",
  "contactName": "Rudi De Marco",
  "contactEmail": "rdemarco@ucdavis.edu"
}

###

### Update an existing Site
PUT {{HostAddress}}/api/{{ApiVersion}}/sites/{{id}}
Content-Type: application/json

{
  "id": "4a9d9369-ea6b-402d-8673-5f77fcda8681",
  "siteStatusCode": "ACTIVE",
  "siteCode": "SITE-DAVIS-DREW-AVE-01"
}

###
