# For more info on HTTP files go to https://aka.ms/vs/httpfile
# An http-client.env.json should be created in the root directory of the project. 
# Select the environment in the upper right corner of this file.

# File level variables
@ApiVersion = v1
@RequestedBy = Fleet.Api.Tests
@id = 55bc2233-8663-45cc-ae71-0eb38c95a7eb
@siteId = 4a9d9369-ea6b-402d-8673-5f77fcda8681

### Get All Stations
GET {{HostAddress}}/api/{{ApiVersion}}/stations

###

### Get Station by ID
GET {{HostAddress}}/api/{{ApiVersion}}/stations/{{id}}

###

### Get Devices for Station by ID
GET {{HostAddress}}/api/{{ApiVersion}}/stations/{{id}}/devices

###

### Get Sensors for Station by ID
GET {{HostAddress}}/api/{{ApiVersion}}/stations/{{id}}/sensors

###

### Create a new Station
POST {{HostAddress}}/api/{{ApiVersion}}/stations
Content-Type: application/json

{
  "stationStatusCode": "ACTIVE",
  "siteId": "{{siteId}}",
  "stationCode": "STN-DREW-AVE",
  "description": "Main development station located at AQMT Drew facility"
}

###

### Update an existing Station
PUT {{HostAddress}}/api/{{ApiVersion}}/stations/{{id}}
Content-Type: application/json

{
  "id": "{{id}}",
  "siteId": "{{siteId}}",
  "stationStatusCode": "ACTIVE",
  "stationCode": "STN-DREW-AVE-01",
  "description": "Main development station located at AQMT Drew facility."
}

###
