// <auto-generated />
using System;
using Fleet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleet.Infrastructure.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260402050735_SeedSystemStatuses")]
    partial class SeedSystemStatuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("metadata")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("device_identifier");

                    b.Property<Guid>("DeviceStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_status_id");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("device_type");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("firmware_version");

                    b.Property<string>("IoTHubDeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("iot_hub_device_id");

                    b.Property<DateTime?>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at_utc");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("mac_address");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceStatusId")
                        .HasDatabaseName("ix_devices_device_status_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_devices_station_id");

                    b.ToTable("devices", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.DeviceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("pk_device_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_device_statuses_code");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("ix_device_statuses_status_name");

                    b.ToTable("device_statuses", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.IntegrationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("default_config_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<Guid>("IntegrationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_type_id");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_integration_templates");

                    b.HasIndex("IntegrationTypeId")
                        .HasDatabaseName("ix_integration_templates_integration_type_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_integration_templates_sensor_type_id");

                    b.ToTable("integration_templates", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.IntegrationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_integration_types");

                    b.ToTable("integration_types", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CalibrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("SensorIdentifier")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("sensor_identifier");

                    b.Property<Guid>("SensorStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_status_id");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_sensors_device_id");

                    b.HasIndex("SensorStatusId")
                        .HasDatabaseName("ix_sensors_sensor_status_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("ix_sensors_station_id");

                    b.ToTable("sensors", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorCalibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibration_date");

                    b.Property<string>("CalibrationMethod")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("calibration_method");

                    b.Property<int>("CalibrationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("calibration_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sensor_calibrations");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_calibrations_sensor_id");

                    b.ToTable("sensor_calibrations", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("IntegrationTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_template_id");

                    b.Property<Guid>("IntegrationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_type_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sensor_integrations");

                    b.HasIndex("IntegrationTemplateId")
                        .HasDatabaseName("ix_sensor_integrations_integration_template_id");

                    b.HasIndex("IntegrationTypeId")
                        .HasDatabaseName("ix_sensor_integrations_integration_type_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_integrations_sensor_id");

                    b.ToTable("sensor_integrations", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("pk_sensor_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_statuses_code");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("ix_sensor_statuses_status_name");

                    b.ToTable("sensor_statuses", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type_name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types");

                    b.ToTable("sensor_types", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("USA")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at_utc");

                    b.Property<DateTime?>("LastMaintenanceAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_maintenance_at_utc");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("postal_code");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("site_name");

                    b.Property<Guid>("SiteStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_status_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("CA")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex("SiteStatusId")
                        .HasDatabaseName("ix_sites_site_status_id");

                    b.ToTable("sites", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SiteStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("pk_site_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_site_statuses_code");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("ix_site_statuses_status_name");

                    b.ToTable("site_statuses", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("station_code");

                    b.Property<Guid>("StationStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_status_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stations");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_stations_site_id");

                    b.HasIndex("StationStatusId")
                        .HasDatabaseName("ix_stations_station_status_id");

                    b.ToTable("stations", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.StationStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("citext")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("citext")
                        .HasColumnName("status_name");

                    b.HasKey("Id")
                        .HasName("pk_station_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_station_statuses_code");

                    b.HasIndex("StatusName")
                        .IsUnique()
                        .HasDatabaseName("ix_station_statuses_status_name");

                    b.ToTable("station_statuses", "metadata");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Device", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.DeviceStatus", "DeviceStatus")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_devices_device_statuses_device_status_id");

                    b.HasOne("Fleet.Domain.Entities.Station", "Station")
                        .WithMany("Devices")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_devices_stations_station_id");

                    b.Navigation("DeviceStatus");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.IntegrationTemplate", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.IntegrationType", "IntegrationType")
                        .WithMany("IntegrationTemplates")
                        .HasForeignKey("IntegrationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_integration_templates_integration_types_integration_type_id");

                    b.HasOne("Fleet.Domain.Entities.SensorType", "SensorType")
                        .WithMany("IntegrationTemplates")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_integration_templates_sensor_types_sensor_type_id");

                    b.Navigation("IntegrationType");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.Device", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_sensors_devices_device_id");

                    b.HasOne("Fleet.Domain.Entities.SensorStatus", "Status")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_sensor_statuses_sensor_status_id");

                    b.HasOne("Fleet.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_sensor_types_sensor_type_id");

                    b.HasOne("Fleet.Domain.Entities.Station", "Station")
                        .WithMany("Sensors")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_stations_station_id");

                    b.Navigation("Device");

                    b.Navigation("SensorType");

                    b.Navigation("Station");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorCalibration", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.Sensor", "Sensor")
                        .WithMany("SensorCalibrations")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_calibrations_sensors_sensor_id");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorIntegration", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.IntegrationTemplate", "IntegrationTemplate")
                        .WithMany("SensorIntegrations")
                        .HasForeignKey("IntegrationTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_integrations_integration_templates_integration_templ");

                    b.HasOne("Fleet.Domain.Entities.IntegrationType", "IntegrationType")
                        .WithMany("SensorIntegrations")
                        .HasForeignKey("IntegrationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_integrations_integration_types_integration_type_id");

                    b.HasOne("Fleet.Domain.Entities.Sensor", "Sensor")
                        .WithMany("SensorIntegrations")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_integrations_sensors_sensor_id");

                    b.Navigation("IntegrationTemplate");

                    b.Navigation("IntegrationType");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Site", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.SiteStatus", "Status")
                        .WithMany("Sites")
                        .HasForeignKey("SiteStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sites_site_statuses_site_status_id");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Station", b =>
                {
                    b.HasOne("Fleet.Domain.Entities.Site", "Site")
                        .WithMany("Stations")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_stations_sites_site_id");

                    b.HasOne("Fleet.Domain.Entities.StationStatus", "Status")
                        .WithMany("Stations")
                        .HasForeignKey("StationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_stations_station_statuses_station_status_id");

                    b.Navigation("Site");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Device", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.DeviceStatus", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.IntegrationTemplate", b =>
                {
                    b.Navigation("SensorIntegrations");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.IntegrationType", b =>
                {
                    b.Navigation("IntegrationTemplates");

                    b.Navigation("SensorIntegrations");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("SensorCalibrations");

                    b.Navigation("SensorIntegrations");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorStatus", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SensorType", b =>
                {
                    b.Navigation("IntegrationTemplates");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Site", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.SiteStatus", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.Station", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Fleet.Domain.Entities.StationStatus", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
